variables:
  RELEASE_BRANCH: master
  GRPC_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  GRPC_RELEASE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - release

default:
  image: docker
  services:
    - name: docker:dind
      # See the comment in https://docs.gitlab.com/ci/runners/hosted_runners/linux/#machine-types-available-for-linux---arm64
      command: ["--mtu=1400"]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-amd64:
  stage: build
  script:
    - docker buildx create --use --platform linux/amd64
    - docker buildx build --platform linux/amd64 -t $GRPC_TAG-amd64 --push .
  timeout: 3 hours
  tags:
    - saas-linux-large-amd64

build-arm64:
  stage: build
  script:
    - docker buildx create --use --platform linux/arm64
    - docker buildx build --platform linux/arm64 -t $GRPC_TAG-arm64 --push .
  timeout: 3 hours
  tags:
    - saas-linux-large-arm64

release:
  stage: release
  script:
    - docker buildx imagetools create -t $GRPC_RELEASE_TAG $GRPC_TAG-amd64 $GRPC_TAG-arm64
  rules:
    - if: $CI_COMMIT_BRANCH == $RELEASE_BRANCH
