variables:
  RELEASE_BRANCH: master
  GRPC_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  GRPC_RELEASE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - release

default:
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --platform linux/amd64,linux/arm64

build:
  stage: build
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t $GRPC_TAG --push .
  timeout: 4 hours
  tags:
    - saas-linux-large-amd64

release:
  stage: release
  script:
    - docker pull $GRPC_TAG
    - docker tag $GRPC_TAG $GRPC_RELEASE_TAG
    - docker push $GRPC_RELEASE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == $RELEASE_BRANCH
