build:
  image: docker
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    GRPC_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $GRPC_TAG .
    - docker push $GRPC_TAG
  only:
    - master
